**Practical 5: Data Extraction and Loading Using Python and Databases**

NAME - Kimi Patle
Class- C1
Batch - A1
Roll No. - 7

PART A: Create Sample Dataset

In [3]:
!pip install pandas sqlalchemy pymysql

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.13/dist-packages (2.0.54)
Collecting pymysql
  Downloading pymysql-1.2.3-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.13/dist-packages (from sqlalchemy) (4.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pymysql-1.2.3-py3-none-any.whl (46 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.7/46.7 kB 1.9 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.3

In [4]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine, text

In [5]:
data = {
    "Student_ID": [101, 102, 103, 104, 105],
    "Name": ["Alice", "Bob", "Charlie", "David", "Kimi"],
    "Department": ["CSE", "CSE","IT", "CSE", "IT"],
    "Marks": [89,99,75,56,78],
    "City": ["Nagpur","Balaghat","Pune", "Mumbai","Bhopal"]
}

df = pd.DataFrame(data)
df

   Student_ID     Name Department  Marks      City
0         101    Alice        CSE     89    Nagpur
1         102      Bob        CSE     99  Balaghat
2         103  Charlie         IT     75      Pune
3         104    David        CSE     56    Mumbai
4         105     Kimi         IT     78    Bhopal

In [6]:
df.to_excel("student.xlsx", index=False)

In [7]:
df.isnull().sum()

Student_ID    0
Name          0
Department    0
Marks         0
City          0
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df = df.drop_duplicates()

In [12]:
df.dtypes

Student_ID     int64
Name          object
Department    object
Marks          int64
City          object
dtype: object

Part B : Sqlite database using splite3

In [13]:
conn = sqlite3.connect("student.db")

In [14]:
df.to_sql(
    "students",
    conn,
    if_exists="replace",
    index=False
)

5

In [16]:
query = """
SELECT * FROM students;
"""

In [17]:
result = pd.read_sql_query(query, conn)
result

   Student_ID     Name Department  Marks      City
0         101    Alice        CSE     89    Nagpur
1         102      Bob        CSE     99  Balaghat
2         103  Charlie         IT     75      Pune
3         104    David        CSE     56    Mumbai
4         105     Kimi         IT     78    Bhopal

In [20]:
query = """
SELECT Student_ID, Name, Marks
FROM students
WHERE Marks> 80;
"""

result = pd.read_sql_query(query, conn)

result

   Student_ID   Name  Marks
0         101  Alice     89
1         102    Bob     99

In [21]:
query = """
SELECT AVG(Marks) AS Average_Marks
FROM students;
"""

pd.read_sql_query(query, conn)

   Average_Marks
0           79.4

In [22]:

query = """
SELECT Department, AVG(Marks) AS Average_Marks
FROM students
GROUP BY Department;
"""

pd.read_sql_query(query, conn)

  Department  Average_Marks
0        CSE      81.333333
1         IT      76.500000

Part C : SQLite using SqlAlchemy

In [23]:
engine = create_engine("sqlite:///student_sqlaichemy.db")

In [26]:
df.to_sql(
    "students",
    engine,
    if_exists="replace",
    index=False
)

5

In [29]:
query = """
SELECT * FROM students;
"""

result = pd.read_sql_query(query, engine)
result

   Student_ID     Name Department  Marks      City
0         101    Alice        CSE     89    Nagpur
1         102      Bob        CSE     99  Balaghat
2         103  Charlie         IT     75      Pune
3         104    David        CSE     56    Mumbai
4         105     Kimi         IT     78    Bhopal

In [31]:
with engine.connect() as connection:
    result = connection.execute(text("SELECT * FROM students WHERE Marks >80"))
    for row in result:
        print(row)

(101, 'Alice', 'CSE', 89, 'Nagpur')
(102, 'Bob', 'CSE', 99, 'Balaghat')

Part D: Import data directly from excel

In [32]:
excel_df = pd.read_excel("student.xlsx")
excel_df.head()

   Student_ID     Name Department  Marks      City
0         101    Alice        CSE     89    Nagpur
1         102      Bob        CSE     99  Balaghat
2         103  Charlie         IT     75      Pune
3         104    David        CSE     56    Mumbai
4         105     Kimi         IT     78    Bhopal

In [33]:
excel_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student_ID  5 non-null      int64
 1   Name        5 non-null      object
 2   Department  5 non-null      object
 3   Marks       5 non-null      int64
 4   City        5 non-null      object
dtypes: int64(2), object(3)
memory usage: 332.0+ bytes

In [35]:
excel_df.isnull().sum()

Student_ID    0
Name          0
Department    0
Marks         0
City          0
dtype: int64

In [36]:
excel_df.duplicated().sum()

np.int64(0)

In [37]:
excel_df.dtypes

Student_ID     int64
Name          object
Department    object
Marks          int64
City          object
dtype: object

Result
The data was successfully extracted, cleaned, processed, and loaded into a
SQLite database using Python. SQL queries were successfully executed using both
sqlite3 and SQLAlchemy. The pandas.to_sql() function was used to load
DataFrame data into database tables. The procedure for connecting Python with
MySQL and PostgreSQL was also studied.